name: Deploy to Vercel

on:
  push:
    branches: [ "master" ]  # Kích hoạt khi push lên branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # Phiên bản Node.js phù hợp

      - name: Build project
        run: npm run build  # Lệnh build tùy vào dự án (ví dụ: `next build`)

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Token từ GitHub Secrets vcp_8i61VMxhgKfetbvzXywzEpdsL2WhrJ2NhlFSWUH1XMBgywWzzd0dMClc
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required team_e17ZPNYa0a0td5htAjCAr97S
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required prj_HDR9h48CkpMhMlJjhBfJIsklSOsr
          vercel-args: '--prod'  # Deploy lên production
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Token mặc định của GitHub